### ISSUE TITLE
Cloper Pearson?

### ISSUE THREAD

**Issue by ghomem** [nolanbconaway/binoculars#3]
For completeness and elegance it would be interesting to also have this method:

https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval#Clopper%E2%80%93Pearson_interval

which, if I understood correctly is the most conservative.

What do you think?

**Comment by nolanbconaway** [comment]
Absolutely!

**Comment by ghomem** [comment]
Do you have plans to implement it?

I just started testing your package and it seems very useful. Thanks in advance.

**Comment by nolanbconaway** [comment]
I'll get around to it eventually! PRs are welcome if you need something faster!

**Comment by ghomem** [comment]
Let's see how far I manage with this. Off topic: why do you use a z-value as the input rather than confidence level?

**Comment by nolanbconaway** [comment]
No particular reason! I find it intuitive so that's what I wrote, but there's no reason a confidence level argument couldn't also be used.

**Comment by nolanbconaway** [comment]
Added in 0.1.3! https://github.com/nolanbconaway/binoculars/pull/4

**Comment by ghomem** [comment]
Awesome. Here is a preview of what I am using binoculars for:

https://lo.gic.li/lgc

I am currently using the default interval.

**Comment by ghomem** [comment]
You still need to document this on the usage section right?

Thanks a lot for this work :-) :muscle:

**Comment by nolanbconaway** [comment]
Cool app! I commonly use site like those when i don't want to pull up my own python envs. I also added these linesto the readme in https://github.com/nolanbconaway/binoculars/pull/6

```py
binomial_confidence(p, N, method='clopper-pearson')
# (0.1266544343411484, 0.291844378634278
```

Enjoy your clopper-pearsons!

**Comment by ghomem** [comment]
Great. I changed my app to use this more conservative Clopper Pearson method. This is very useful.
